### ISSUE TITLE
Runs on Android?

### ISSUE THREAD

**Issue by phxql** [phxql/argon2-jvm#44]
I've added support for ARM and ARM64 libraries, so it should be possible to run that on Android. Can someone, who is an Android developer, check this? Thanks!

**Comment by rijulluman** [comment]
@phxql 
In the settings.gradle of the Main Android Project,
I have added the argon2-jvm reference:
include ':app'
include ':argon2-jvm'
project(':argon2-jvm').projectDir = new File(settingsDir, '../argon2-jvm')

So now the project compiles correctly, but when I check the newly created argon2-jvm-2.3.jar, it has only darwin, linux and win32 .so files... No files are created for the mobile processor...
Any suggestions on how I can create them?

**Comment by Embraser01** [comment]
I just tested it and It doesn't work, I got this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.heptabargames.a7isenough, PID: 32338
                  java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource path (.)
                      at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
                      at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
                      at com.sun.jna.Native.<clinit>(Native.java:190)
                      at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35)
                      at de.mkammerer.argon2.Argon2Factory$Argon2Types.<init>(Argon2Factory.java:137)
                      at de.mkammerer.argon2.Argon2Factory$Argon2Types.<clinit>(Argon2Factory.java:119)
                      at de.mkammerer.argon2.Argon2Factory.create(Argon2Factory.java:21)
                      at com.heptabargames.a7isenough.services.BeaconService.checkBeacon(BeaconService.java:28)
                      at com.heptabargames.a7isenough.MainActivity.onActivityResult(MainActivity.java:234)
                      at android.app.Activity.dispatchActivityResult(Activity.java:7692)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4918)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4965)
                      at android.app.ActivityThread.-wrap20(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940)
                      at android.os.Handler.dispatchMessage(Handler.java:108)
                      at android.os.Looper.loop(Looper.java:166)
                      at android.app.ActivityThread.main(ActivityThread.java:7415)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```

The `Argon2Factory.create()` fail

I'm on Android 8.0.0

**Comment by rijulluman** [comment]
Try this:
https://github.com/marcoh00/argon2jni

**Comment by Embraser01** [comment]
Ok thanks! I tried it, but I now have a runtime error...

I will change the algorithm for simplicity

**Comment by rijulluman** [comment]
@Embraser01 Incase you just downloaded a zip from github, you need to do a recursive clone... That project is dependent on the c implementation.

**Comment by Embraser01** [comment]
Yeah, I did that 😅 
But I didn't really searched why as I don't have much time to finish my project (I must send it by Friday)

**Comment by phxql** [comment]
Ok, apparently Android uses another architecture, separate from ARM64.

**Comment by tuancoltech** [comment]
Hi @phxql , do you have any plan for supporting Android arm 64 bit architecture `arm64-v8a` ?
We currently have this similar issue when running in 64 bit device.

Thanks.

**Comment by phxql** [comment]
I have to see if i can compile the argon2 lib on an Android device. If I get this to work, I think argon2-jvm would work on android.

**Comment by lambdapioneer** [comment]
I ran into this issue last year and built a binding specific for Android: https://github.com/lambdapioneer/argon2kt

Just wanted to leave this here as a pointer for the next developer looking into this :)
