### ISSUE TITLE
Choose Argon Version

### ISSUE THREAD

**Issue by konsultaner** [phxql/argon2-jvm#47]
The c-lib for Argon supports to choose a version

> ``` -v (10|13)      Argon2 version (defaults to the most recent version, currently 13) ```

The WAMP-Protocol is currently working on a new [Authentication mechanism called WAMP-SCRAM that uses Argon2](https://github.com/wamp-proto/wamp-proto/issues/135). There it is possible to choose the version. I want to use your Java binding to implement it with this possibility. Therefore it would be nice if you could offer this to choose in the `createAdvanced(...)` method.

**Comment by smartwjw** [comment]
I encounter a problem at centos 6：

```
Exception in thread "grpc-worker-1" java.lang.UnsatisfiedLinkError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/jna-3506402/jna2770040720613788704.tmp)
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
```

Please improve document to indicate compatible matrix.

**Comment by phxql** [comment]
I don't think that this is related to Argon2 internal version choosing, please open a separate ticket for that. Thanks.

**Comment by phxql** [comment]
Implemented, will be released in the next version. See the `hashAdvanced` method in `Argon2Advanced`.
