### ISSUE TITLE
 Document compatible matrix

### ISSUE THREAD

**Issue by wangjunwei87** [phxql/argon2-jvm#48]
I encounter a problem at centos 6：

```
Exception in thread "grpc-worker-1" java.lang.UnsatisfiedLinkError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/jna-3506402/jna2770040720613788704.tmp)
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
```

I don't know which version is work on CentOS 6, please improve document to indicate compatible matrix.

https://github.com/phxql/argon2-jvm/issues/47#issuecomment-372006499

**Comment by phxql** [comment]
I have tested Argon2-JVM 2.7 against a load of distributions: https://github.com/phxql/argon2-jvm/blob/develop/compatibility-tests/README.md

I have also added a workaround for CentOS 6.
